format = "$all"
  
  [line_break]
  disabled = true
  
  [python]
  format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\))]($style)'
  symbol = " "
  style = "yellow bold"
  pyenv_prefix = "pyenv"
  version_format = "v${raw}"
  #virtualenv = "venv"
